// clang-format off
// NOLINTBEGIN
// GENERATED BY NNCBINDGEN from ssl/ssl_Context.h
#pragma once

#include <stdint.h>
#include <stdbool.h>

#include <nn/nn_Result.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum nnsslContextSslVersion {
    nnsslContextSslVersion_Auto = 0x01,
    nnsslContextSslVersion_v10 = 0x08,
    nnsslContextSslVersion_v11 = 0x10,
    nnsslContextSslVersion_v12 = 0x20,
    nnsslContextSslVersion_v13 = 0x40,
    nnsslContextSslVersion_Auto24 = 0x1000000,
} nnsslContextSslVersion;

typedef union nnsslContext { void* buf[0x10]; void* alignment_holder; } nnsslContext;

nnResult nnsslContextCreate(nnsslContext* this_, nnsslContextSslVersion version);
nnResult nnsslContextDestroy(nnsslContext* this_);
nnResult nnsslContextGetContextId(nnsslContext* this_, uint64_t* outId);

#ifdef __cplusplus
}
#endif

// NOLINTEND
// clang-format off
