// clang-format off
// NOLINTBEGIN
// GENERATED BY NNCBINDGEN from ssl/ssl_Connection.h
#pragma once

#include <stdint.h>
#include <stdbool.h>

#include <nn/ssl/ssl_Context.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum nnsslConnectionVerifyOption {
    nnsslConnectionVerifyOption_PeerCa = 1 << 0,
    nnsslConnectionVerifyOption_HostName = 1 << 1,
    nnsslConnectionVerifyOption_DateCheck = 1 << 2,
    nnsslConnectionVerifyOption_EvCertPartial = 1 << 3,
    nnsslConnectionVerifyOption_EvPolicyOid = 1 << 4,
    nnsslConnectionVerifyOption_EvCertFingerprint = 1 << 5,
} nnsslConnectionVerifyOption;

typedef enum nnsslConnectionIoMode {
    nnsslConnectionIoMode_Blocking = 1,
    nnsslConnectionIoMode_NonBlocking = 2,
} nnsslConnectionIoMode;

typedef enum nnsslConnectionSessionCacheMode {
    nnsslConnectionSessionCacheMode_None,
    nnsslConnectionSessionCacheMode_SessionId,
    nnsslConnectionSessionCacheMode_SessionTicket,
} nnsslConnectionSessionCacheMode;

typedef union nnsslConnection { void* buf[0x10]; void* alignment_holder; } nnsslConnection;

typedef enum nnsslConnectionPollEvent {
    nnsslConnectionPollEvent_Read = 1 << 0,
    nnsslConnectionPollEvent_Write = 1 << 1,
    nnsslConnectionPollEvent_Except = 1 << 2,
} nnsslConnectionPollEvent;

typedef enum nnsslConnectionOptionType {
    nnsslConnectionOptionType_DoNotCloseSocket,
    nnsslConnectionOptionType_GetServerCertChain,
    nnsslConnectionOptionType_SkipDefaultVerify,
    nnsslConnectionOptionType_EnableAlpn,
} nnsslConnectionOptionType;

typedef union nnsslConnectionServerCertDetail { uint8_t buf[0x1]; char alignment_holder; } nnsslConnectionServerCertDetail;

nnResult nnsslConnectionCreate(nnsslConnection* this_, nnsslContext* context);
nnResult nnsslConnectionDestroy(nnsslConnection* this_);
nnResult nnsslConnectionSetSocketDescriptor(nnsslConnection* this_, int32_t socketDescriptor);
nnResult nnsslConnectionSetHostName(nnsslConnection* this_, const char* hostName, uint32_t hostNameSize);
nnResult nnsslConnectionSetVerifyOption(nnsslConnection* this_, nnsslConnectionVerifyOption verifyOption);
nnResult nnsslConnectionSetServerCertBuffer(nnsslConnection* this_, const char* serverCertificateBuffer, uint32_t serverCertificateBufferSize);
nnResult nnsslConnectionSetIoMode(nnsslConnection* this_, nnsslConnectionIoMode ioMode);
nnResult nnsslConnectionSetSessionCacheMode(nnsslConnection* this_, nnsslConnectionSessionCacheMode sessionCacheMode);
nnResult nnsslConnectionGetSocketDescriptor(nnsslConnection* this_, int32_t* outSocketDescriptor);
nnResult nnsslConnectionGetHostName(nnsslConnection* this_, const char* outHostName, uint32_t* outHostNameSize, uint32_t maxHostNameSize);
nnResult nnsslConnectionGetVerifyOption(nnsslConnection* this_, nnsslConnectionVerifyOption* outVerifyOption);
nnResult nnsslConnectionGetIoMode(nnsslConnection* this_, nnsslConnectionIoMode* outIoMode);
nnResult nnsslConnectionDoHandshake(nnsslConnection* this_);
nnResult nnsslConnectionDoHandshakeWithCertBuffer(nnsslConnection* this_, uint32_t* outServerCertificateBufferSize, uint32_t* outNumCertificates);
nnResult nnsslConnectionDoHandshakeWithBuffer(nnsslConnection* this_, uint32_t* outServerCertificateBufferSize, uint32_t* outNumCertificates, char* outServerCertificateBuffer, uint32_t serverCertificateBufferMaxSize);
nnResult nnsslConnectionGetServerCertDetail(nnsslConnection* this_, nnsslConnectionServerCertDetail*, const char*, uint32_t);
nnResult nnsslConnectionRead(nnsslConnection* this_, char* outBuffer, int32_t* outBufferSize, uint32_t maxBufferSize);
nnResult nnsslConnectionWrite(nnsslConnection* this_, const char* buffer, int32_t* outWrittenBufferSize, uint32_t maxBufferSize);
nnResult nnsslConnectionPending(nnsslConnection* this_, int32_t*);
nnResult nnsslConnectionPeek(nnsslConnection* this_, char* outBuffer, int32_t* outBufferSize, uint32_t maxBufferSize);
nnResult nnsslConnectionPoll(nnsslConnection* this_, nnsslConnectionPollEvent*, nnsslConnectionPollEvent*, uint32_t timeout);
nnResult nnsslConnectionGetVerifyCertError(nnsslConnection* this_, nnResult* outErrorResult);
nnResult nnsslConnectionGetContextId(nnsslConnection* this_, uint64_t* outContextId);
nnResult nnsslConnectionGetConnectionId(nnsslConnection* this_, uint64_t* outConnectionId);
nnResult nnsslConnectionSetOption(nnsslConnection* this_, nnsslConnectionOptionType option, bool value);
nnResult nnsslConnectionGetOption(nnsslConnection* this_, bool* outValue, nnsslConnectionOptionType option);

#ifdef __cplusplus
}
#endif

// NOLINTEND
// clang-format off
