// clang-format off
// NOLINTBEGIN
// GENERATED BY NNCBINDGEN from ssl.h
#pragma once

#include <stdint.h>
#include <stdbool.h>

#include <nn/nn_Result.h>
#include <nn/ssl/ssl_Connection.h>
#include <nn/ssl/ssl_Context.h>

#ifdef __cplusplus
extern "C" {
#endif

    struct nnsslBackend  // TODO: Validate members
{
    union nnsslConnection connection;
    union nnsslContext context;
    union nnsslContext* pnnssl_context; /* active context (embedded or external) */
    char using_external_ssl_context;
    int value;
};

nnResult nnsslInitialize();
nnResult nnsslInitializeWithConcurrencyLimit(uint32_t concurrencyLimit);
nnResult nnsslFinalize();

#ifdef __cplusplus
}
#endif

// NOLINTEND
// clang-format off
